### ISSUE TITLE
Kind of sabotage appears as Available under Therapist

### ISSUE THREAD

**Issue by Pearcekieser** [TarkovTracker/tarkovdata#29]
On tarkovTracker the [Kind of sabotage](https://escapefromtarkov.gamepedia.com/Kind_of_sabotage) quest appears under Therapist as an Available quest, when I go to check it off I was expecting to find it under Skier.  

I think the [data](https://github.com/TarkovTracker/tarkovdata/blob/master/quests.json#L1008-L1010) in the quests.json seems accurate.  Might be on the front end, choosing to group quests by giver, rather than the turnin.  My normal interaction w TarkovTracker is for turning in quests after completing them in game, I think it would make more sense to display the quests grouped by turnin.  

Also, I'm happy to help with the fix / get involved in supporting tarkovTracker.  I think this tool is a good service to the Tarkov community.  I didn't find the code for the front-end to investigate this further.

**Comment by thaddeus** [comment]
Yeah, that makes total sense that that's where you'd expect to go to finish the quest. I'm trying to remember why I marked this as Therapist being the quest giver - its possible it was an error, but I remember when I was initially creating the quests data that there were a couple anomalies where the giver != turnin trader. I'll double check when the servers are back up.

As for contributing, would love to have you. I'm very close to open sourcing the site - I'm not a frontend guy, and as such started the site by purchasing some templates and front-end resources to help quickstart me and help me learn. I didn't have source redistribution rights for some of those things which is why it hasn't been open-sourced as of yet, I'm very close as I got my last issue sorted out. A tiny bit of work to replace the last thing but should be on the order of a week or so.
