### ISSUE TITLE
Tarkov Item Language System

### ISSUE THREAD

**Issue by MypowerHD** [TarkovTracker/tarkovdata#63]
Issue Description:
https://github.com/TarkovTracker/tarkovdata/blob/4a5a7a900c538e069389c5778134c590eaed6162/items.en.json#L2
Is there any reason while your using Properties instead of Simple Object Array?

**Comment by thaddeus** [comment]
IIRC correctly, we opted for this because the normal use case would be looking up an object by its ID. So with this format, most situations would be `itemData[itemId].name` instead of `itemData.filter(item => item.id == itemId)[0]` It isn't elegant, for sure, as there is the risk of the field of the parent object could become out of line with the child object's ID. I'm not opposed to it being either way.

**Comment by MypowerHD** [comment]
> as there is the risk of the field of the parent object could become out of line with the child object's ID

i don't see there any risks, can you show me an example where this case happening? 
Mabye it help me to understand that because never seen that case before.

please don't understand me wrong, i only want to understand what case can happen, because i've never seen something like that before and it was little bit wired to see something like that.

**Comment by thaddeus** [comment]
> i don't see there any risks, can you show me an example where this case happening?

Sorry, I meant it as a theoretical. I was admitting this method of data storage has a theoretical risk that when someone updating or adding to it, could make a human error of manipulating one ID without the other, causing them to be out of sync, which isn't desirable.

**Comment by MypowerHD** [comment]
yeah fore sure it can, but i thought you dump the id's out of EFT and don't pick them by urself^^

**Comment by kokarn** [comment]
We do, but somebody else might not or might do a copy-paste where they miss a character etc

**Comment by thaddeus** [comment]
Closing for now - can be revisited in a Discussion to be changed
